# .github/actions/setup-kubectl/action.yaml
name: 'Setup kubectl'
description: 'Install and configure kubectl with cluster access'

inputs:
  kube-config:
    description: 'Base64 encoded kubeconfig'
    required: true

runs:
  using: 'composite'
  steps:
    - name: ðŸ”§ Install kubectl
      shell: bash
      run: |
        if ! command -v kubectl &> /dev/null; then
          curl -sLO "https://dl.k8s.io/release/$(curl -sL https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          mkdir -p ~/.local/bin
          mv kubectl ~/.local/bin/
          echo "$HOME/.local/bin" >> $GITHUB_PATH
        fi

    - name: ðŸ” Configure kubectl
      shell: bash
      run: |
        mkdir -p ~/.kube
        echo "${{ inputs.kube-config }}" | base64 -d > ~/.kube/config
        chmod 600 ~/.kube/config
        kubectl cluster-info --request-timeout=5s
