name: 📝 Documentation
description: Create, update, or improve documentation
title: "[DOCS] "
labels: ["type:documentation"]
type: "Documentation"
body:
  - type: textarea
    id: purpose
    attributes:
      label: Purpose & Scope
      description: What documentation is needed and why?
      placeholder: |
        What: [what documentation needs to be created/updated]
        Why: [problem this solves]
        Audience: [who will use this - developers, operators, users]
        Scope: [what topics to cover]
    validations:
      required: true

  - type: textarea
    id: completion_criteria
    attributes:
      label: Completion Criteria
      description: How will we know this documentation work is done?
      placeholder: |
        - [ ] Content is written and accurate
        - [ ] Examples and code snippets are tested
        - [ ] Formatting is consistent with existing docs
        - [ ] Published to correct location
        - [ ] Peer reviewed
    validations:
      required: true

  - type: textarea
    id: content_outline
    attributes:
      label: Content Outline
      description: Rough structure or table of contents
      placeholder: |
        1. Overview/Introduction
        2. Prerequisites
        3. Main content sections...
        4. Examples
        5. Troubleshooting (if needed)
    validations:
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Dependencies, existing docs, references, or other notes
      placeholder: |
        - Dependencies: [what must be done first]
        - Current state: [existing docs location/status]
        - References: [links to examples, style guides]
        - Format: [markdown, wiki, etc.]
        - Location: [where to publish]
    validations:
      required: false
