name: 🏛️ Epic
description: High-level technical domains that group related features
title: "[EPIC] "
labels: ["type: epic"]
body:
  - type: input
    id: epic_title
    attributes:
      label: Epic Title
      description: Technical domain or major capability area
      placeholder: "e.g., MLOps Training Platform, Security & Authentication"
    validations:
      required: true
      
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What technical domain does this epic cover? What's the overall goal?
      placeholder: "This epic encompasses all components and capabilities needed for..."
    validations:
      required: true
      
  - type: textarea
    id: context
    attributes:
      label: Context & Notes
      description: Dependencies, constraints, or additional context
      placeholder: "Optional: key dependencies, timeline considerations, etc."
    validations:
      required: false