name: 🏛️ Epic
description: High-level technical domains that group related features
title: "[EPIC] "
labels: ["type:epic"]
type: "Epic"
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What technical domain does this epic cover? What's the overall goal?
      placeholder: "This epic encompasses all components and capabilities needed for..."
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context & Notes
      description: Dependencies, constraints, or additional context
      placeholder: "Optional: key dependencies, timeline considerations, etc."
    validations:
      required: false
