name: 🏛️ Epic
description: Large work packages that span multiple features and possibly milestones
title: "[EPIC] "
labels: ["type: epic"]
body:
  - type: input
    id: epic_title
    attributes:
      label: Epic Title
      description: Clear, concise title for this epic
      placeholder: "e.g., MLOps Core Platform, Infrastructure Foundation"
    validations:
      required: true

  - type: textarea
    id: problem_statement
    attributes:
      label: Problem Statement
      description: What problem does this epic solve? Why is it needed?
      placeholder: "Describe the business/technical problem this epic addresses..."
    validations:
      required: true

  - type: textarea
    id: success_criteria
    attributes:
      label: Success Criteria
      description: How will we know this epic is complete and successful?
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Criterion 3
    validations:
      required: true

  - type: textarea
    id: scope
    attributes:
      label: Scope & Key Features
      description: What are the main features/components included in this epic?
      placeholder: |
        In Scope:
        - Feature A
        - Feature B
        
        Out of Scope:
        - Feature X (for later epic)
        - Feature Y (not needed)
    validations:
      required: true

  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies
      description: What other epics, features, or external factors does this depend on?
      placeholder: |
        Depends on:
        - Epic: Infrastructure Foundation
        - External: Cloud provider setup
        
        Blocks:
        - Epic: Advanced ML Capabilities
    validations:
      required: false

  - type: textarea
    id: assumptions
    attributes:
      label: Assumptions & Constraints
      description: Key assumptions and known constraints
      placeholder: |
        Assumptions:
        - Local development on kind cluster
        - Single developer initially
        
        Constraints:
        - Timeline: Must complete by [date]
        - Resources: Local machine limitations
    validations:
      required: false

  - type: dropdown
    id: size_estimate
    attributes:
      label: Size Estimate
      description: Rough estimate of epic size
      options:
        - S (1-2 weeks)
        - M (3-4 weeks)
        - L (1-2 months)
        - XL (2+ months)
    validations:
      required: true

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Links to documentation, research, or other relevant information
      placeholder: |
        - Documentation: [link]
        - Research: [link]
        - Related issues: #123, #456