name: 🧩 Feature
description: User-facing functionality or significant component implementation
title: "[FEATURE] "
labels: ["type:feature"]
type: "Feature"
body:
  - type: input
    id: feature_title
    attributes:
      label: Feature Title
      description: Clear, user-focused title for this feature
      placeholder: "e.g., MLflow Model Registry, ArgoCD ApplicationSets"
    validations:
      required: true

  - type: textarea
    id: user_story
    attributes:
      label: User Story
      description: As a [user type], I want [functionality] so that [benefit]
      placeholder: |
        As a data scientist, I want to register my trained models in MLflow so that I can version and deploy them consistently.
    validations:
      required: true

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      description: Specific, testable conditions that define feature completion
      placeholder: |
        - [ ] Users can register models with metadata and versioning
        - [ ] Model artifacts are stored in object storage
        - [ ] Feature integrates with existing authentication
        - [ ] Monitoring and logging are functional
        - [ ] Documentation covers usage scenarios
    validations:
      required: true

  - type: textarea
    id: technical_scope
    attributes:
      label: Technical Scope
      description: High-level technical components and integrations
      placeholder: |
        Components:
        - MLflow server deployment
        - Database integration
        - Object storage configuration
        
        Integrations:
        - Istio service mesh
        - Keycloak authentication
        - Prometheus monitoring
    validations:
      required: true

  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies
      description: What features or external factors must be ready first?
      placeholder: |
        - Feature: #456 (Database Infrastructure)
        - Feature: #789 (Object Storage Setup)
        - External: Container registry access
    validations:
      required: false

  - type: textarea
    id: testing_strategy
    attributes:
      label: Testing Strategy
      description: How will this feature be validated end-to-end?
      placeholder: |
        - Integration testing with dependent services
        - End-to-end user workflow testing
        - Performance and load considerations
        - Security and access control validation
    validations:
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Design docs, research, or reference materials
      placeholder: |
        - Architecture diagram: [link]
        - API documentation: [link]
        - Related research: [link]
    validations:
      required: false