name: 🔬 Research
description: Investigation, analysis, or knowledge gathering needed
title: "[RESEARCH] "
labels: ["type:research"]
type: "Research"
body:
  - type: input
    id: research_title
    attributes:
      label: Research Title
      description: Clear title describing what needs to be researched
      placeholder: "e.g., Evaluate BERT vs DistilBERT for text classification"
    validations:
      required: true

  - type: textarea
    id: research_question
    attributes:
      label: Research Question & Context
      description: What needs to be answered and why?
      placeholder: |
        Question: [main question to answer]
        Why: [why this research is needed]
        Impact: [what decisions this will inform]
    validations:
      required: true

  - type: textarea
    id: scope_and_approach
    attributes:
      label: Scope & Approach
      description: What will be investigated and how?
      placeholder: |
        Scope:
        - [what to investigate]
        - [what tools/technologies to evaluate]
        
        Approach:
        - [methodology - literature review, testing, comparison]
        - [resources needed - tools, access, experts]
    validations:
      required: true

  - type: textarea
    id: success_criteria
    attributes:
      label: Success Criteria & Deliverables
      description: How will we know this research is complete?
      placeholder: |
        Success criteria:
        - [ ] Research question answered with confidence
        - [ ] Recommendations documented with rationale
        - [ ] Proof-of-concept implemented (if applicable)
        
        Deliverables:
        - Research report with findings
        - Decision framework or comparison
        - Updated documentation
    validations:
      required: true

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Dependencies, related work, timeline, or other notes
      placeholder: |
        - Dependencies: [what's needed before starting]
        - Related issues: #123, #456
        - References: [documentation, similar implementations]
        - Timeline considerations: [any constraints]
    validations:
      required: false