name: 📌 Task
description: Specific implementation work with clear deliverables
title: "[TASK] "
labels: ["type:task"]
type: "Task"
body:
  - type: input
    id: task_title
    attributes:
      label: Task Title
      description: Specific, actionable implementation task
      placeholder: "e.g., Deploy MLflow server with PostgreSQL backend"
    validations:
      required: true

  - type: textarea
    id: implementation_description
    attributes:
      label: Implementation Description
      description: What exactly needs to be built/configured/deployed?
      placeholder: |
        Create Helm values configuration for MLflow server deployment with:
        - PostgreSQL backend connection
        - MinIO artifact storage
        - Istio sidecar injection
        - RBAC service account
    validations:
      required: true

  - type: textarea
    id: deliverables
    attributes:
      label: Deliverables
      description: Concrete outputs that define task completion
      placeholder: |
        - [ ] Helm values.yaml file created
        - [ ] MLflow pod running in cluster
        - [ ] Database connection verified
        - [ ] Web UI accessible via ingress
        - [ ] Basic smoke test passing
    validations:
      required: true

  - type: textarea
    id: implementation_details
    attributes:
      label: Implementation Details
      description: Specific files, commands, and configuration details
      placeholder: |
        Files to create/modify:
        - charts/mlflow/values.yaml
        - scripts/deploy-mlflow.sh
        
        Key configurations:
        - Database URL: postgresql://...
        - Storage backend: s3://minio-bucket
        - Service port: 5000
        
        Commands:
        - helm install mlflow ./charts/mlflow
        - kubectl port-forward svc/mlflow 5000:5000
    validations:
      required: false

  - type: textarea
    id: verification_checklist
    attributes:
      label: Verification Checklist
      description: Step-by-step verification that the task works
      placeholder: |
        1. Check pod status: kubectl get pods -l app=mlflow
        2. Verify logs: kubectl logs deployment/mlflow
        3. Test web UI: curl http://mlflow.local/health
        4. Test API: curl http://mlflow.local/api/2.0/experiments/list
        5. Confirm database connection in UI
    validations:
      required: false

  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies
      description: What must be completed before starting this task?
      placeholder: |
        - Task: #789 (Deploy PostgreSQL cluster)
        - Task: #790 (Configure MinIO bucket)
        - Resource: Helm chart repository access
    validations:
      required: false



  - type: textarea
    id: notes
    attributes:
      label: Implementation Notes
      description: Technical gotchas, references, or special considerations
      placeholder: |
        References:
        - MLflow Helm chart: [link]
        - Configuration docs: [link]
        
        Notes:
        - Ensure persistent volume claims are created first
        - May need to adjust resource limits for local cluster
    validations:
      required: false