name: 📌 Task
description: Specific implementation work or technical activities
title: "[TASK] "
labels: ["type: task"]
body:
  - type: input
    id: task_title
    attributes:
      label: Task Title
      description: Specific, actionable title for this task
      placeholder: "e.g., Configure ArgoCD RBAC, Write Helm chart for MLflow"
    validations:
      required: true

  - type: dropdown
    id: team
    attributes:
      label: Owning Team
      description: Which team will complete this task?
      options:
        - platform
        - ai
        - app
        - thesis
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How urgent is this task?
      options:
        - critical
        - high
        - medium
        - low
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which system component does this task affect?
      options:
        - infra
        - gitops
        - cicd
        - ai-platform
        - ai-models
        - security
        - observability
        - storage
        - demo-app
    validations:
      required: true

  - type: input
    id: parent_feature
    attributes:
      label: Parent Feature/Epic
      description: Which feature or epic does this task belong to?
      placeholder: "e.g., #123 (Feature: MLflow Deployment)"
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: Task Description
      description: Clear description of what needs to be done
      placeholder: |
        Specific work to be completed...
        
        Context: Why this task is needed
        Approach: How it should be implemented
    validations:
      required: true

  - type: textarea
    id: completion_criteria
    attributes:
      label: Completion Criteria
      description: How will we know this task is done?
      placeholder: |
        - [ ] Configuration files created/updated
        - [ ] Code changes implemented
        - [ ] Tests passing
        - [ ] Documentation updated
        - [ ] Deployed and verified in cluster
    validations:
      required: true

  - type: textarea
    id: technical_details
    attributes:
      label: Technical Details
      description: Specific technical requirements or implementation notes
      placeholder: |
        - File locations: [path/to/files]
        - Configuration keys: [specific settings]
        - Code changes needed: [brief description]
        - Commands to run: [if applicable]
    validations:
      required: false

  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies
      description: What must be completed before this task can start?
      placeholder: |
        - Task: #456 (Install cert-manager)
        - External: Access to container registry
        - Knowledge: Understanding of Istio configuration
    validations:
      required: false

  - type: dropdown
    id: size_estimate
    attributes:
      label: Size Estimate
      description: Expected time to complete this task
      options:
        - XS (< 2 hours)
        - S (2-4 hours)
        - M (4-8 hours)
        - L (1-2 days)
        - XL (2+ days)
    validations:
      required: true

  - type: checkboxes
    id: task_type
    attributes:
      label: Task Type
      description: What kind of work is this?
      options:
        - label: Configuration/Setup
        - label: Code Implementation
        - label: Documentation
        - label: Testing/Validation
        - label: Deployment/Operations
        - label: Research/Investigation

  - type: textarea
    id: verification_steps
    attributes:
      label: Verification Steps
      description: How to test/verify the task is working correctly
      placeholder: |
        1. Run command: [specific command]
        2. Check output: [expected result]
        3. Verify in UI: [what to look for]
        4. Test functionality: [specific test]
    validations:
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Links, references, or other relevant information
      placeholder: |
        - Documentation: [link]
        - Related PRs: [link]
        - Reference implementation: [link]