# .github/actions/resolve-dvc-version/action.yaml
name: 'Resolve DVC Data Version'
description: 'Resolve DVC data version - validates tags and optionally verifies data exists in remote'

inputs:
  dataset:
    description: 'Dataset name (e.g., opencloudhub-readmes, emotion, wine-quality)'
    required: true
  version:
    description: 'Version to resolve - "latest" for most recent, or specific (e.g., v1.0.0)'
    required: true
    default: 'latest'
  dvc-repo:
    description: 'DVC repository URL'
    required: true
  verify-remote:
    description: 'Verify data exists in remote storage (requires AWS creds)'
    required: false
    default: 'false'
  aws-access-key-id:
    description: 'AWS access key (required if verify-remote is true)'
    required: false
    default: ''
  aws-secret-access-key:
    description: 'AWS secret key (required if verify-remote is true)'
    required: false
    default: ''
  aws-endpoint-url:
    description: 'S3 endpoint URL (for MinIO)'
    required: false
    default: ''

outputs:
  resolved-version:
    description: 'Resolved version (e.g., v1.0.0)'
    value: ${{ steps.resolve-tag.outputs.resolved-version }}
  full-tag:
    description: 'Full git tag (e.g., opencloudhub-readmes-v1.0.0)'
    value: ${{ steps.resolve-tag.outputs.full-tag }}
  dataset:
    description: 'Dataset name (pass-through for convenience)'
    value: ${{ inputs.dataset }}

runs:
  using: 'composite'
  steps:
    # =========================================================================
    # Step 1: Resolve git tag (latest or specific)
    # =========================================================================
    - name: 🏷️ Resolve git tag
      id: resolve-tag
      shell: bash
      run: |
        DATASET="${{ inputs.dataset }}"
        VERSION="${{ inputs.version }}"
        DVC_REPO="${{ inputs.dvc-repo }}"

        echo "🔍 Resolving DVC data version..."
        echo "   Dataset: ${DATASET}"
        echo "   Version: ${VERSION}"
        echo "   Repository: ${DVC_REPO}"
        echo ""

        # Get all tags for this dataset
        echo "📋 Fetching tags from repository..."
        ALL_TAGS=$(git ls-remote --tags "${DVC_REPO}" 2>/dev/null \
          | grep "refs/tags/${DATASET}-v" \
          | sed 's/.*refs\/tags\///' \
          | grep -v '\^{}' \
          | sort -V)

        if [ -z "$ALL_TAGS" ]; then
          echo "❌ No tags found for dataset '${DATASET}'"
          echo "   Expected tag pattern: ${DATASET}-v*"
          echo ""
          echo "   Available tags in repo:"
          git ls-remote --tags "${DVC_REPO}" 2>/dev/null \
            | sed 's/.*refs\/tags\///' \
            | grep -v '\^{}' \
            | head -20 || echo "   (none or repo not accessible)"
          exit 1
        fi

        TAG_COUNT=$(echo "$ALL_TAGS" | wc -l | tr -d '[:space:]')
        echo "   Found ${TAG_COUNT} tags for ${DATASET}"

        if [ "${VERSION}" = "latest" ]; then
          FULL_TAG=$(echo "$ALL_TAGS" | tail -1)
          RESOLVED_VERSION=$(echo "$FULL_TAG" | sed "s/${DATASET}-//")
          echo "✅ Latest version: ${RESOLVED_VERSION}"
        else
          FULL_TAG="${DATASET}-${VERSION}"

          if ! echo "$ALL_TAGS" | grep -q "^${FULL_TAG}$"; then
            echo "❌ Tag not found: ${FULL_TAG}"
            echo ""
            echo "   Available versions for ${DATASET}:"
            echo "$ALL_TAGS" | tail -10 | sed "s/${DATASET}-/   /"
            exit 1
          fi

          RESOLVED_VERSION="${VERSION}"
          echo "✅ Tag exists: ${FULL_TAG}"
        fi

        echo "resolved-version=${RESOLVED_VERSION}" >> $GITHUB_OUTPUT
        echo "full-tag=${FULL_TAG}" >> $GITHUB_OUTPUT

    # =========================================================================
    # Step 2: Verify DVC tracking exists (.dvc files or dvc.lock)
    # =========================================================================
    - name: 📂 Check DVC tracking
      id: check-tracking
      shell: bash
      run: |
        DATASET="${{ inputs.dataset }}"
        FULL_TAG="${{ steps.resolve-tag.outputs.full-tag }}"
        DVC_REPO="${{ inputs.dvc-repo }}"

        echo "📂 Checking for DVC tracking at tag ${FULL_TAG}..."

        # Sparse checkout to check for DVC tracking files
        TEMP_DIR=$(mktemp -d)
        cd "${TEMP_DIR}"

        git init -q
        git remote add origin "${DVC_REPO}"
        git config core.sparseCheckout true

        cat > .git/info/sparse-checkout << EOF
        data/${DATASET}/
        pipelines/${DATASET}*/
        EOF

        if ! git fetch -q --depth 1 origin "refs/tags/${FULL_TAG}" 2>/dev/null; then
          echo "❌ Failed to fetch tag ${FULL_TAG}"
          rm -rf "${TEMP_DIR}"
          exit 1
        fi

        git checkout -q FETCH_HEAD 2>/dev/null

        # Count .dvc files
        DVC_FILE_COUNT=0
        if [ -d "data/${DATASET}" ]; then
          DVC_FILE_COUNT=$(find "data/${DATASET}" -name "*.dvc" 2>/dev/null | wc -l | tr -d '[:space:]')
        fi

        # Count dvc.lock files
        LOCK_FILE_COUNT=0
        LOCK_FILES=""
        if [ -d "pipelines" ]; then
          LOCK_FILES=$(find "pipelines" -path "*${DATASET}*" -name "dvc.lock" 2>/dev/null || true)
          if [ -n "$LOCK_FILES" ]; then
            LOCK_FILE_COUNT=$(echo "$LOCK_FILES" | wc -l | tr -d '[:space:]')
          fi
        fi

        # Validate we found something
        if [ "$DVC_FILE_COUNT" -eq 0 ] && [ "$LOCK_FILE_COUNT" -eq 0 ]; then
          echo "❌ No DVC tracking found for dataset '${DATASET}' at tag ${FULL_TAG}"
          echo "   Checked for:"
          echo "   - .dvc files in data/${DATASET}/"
          echo "   - dvc.lock files in pipelines/${DATASET}*/"
          rm -rf "${TEMP_DIR}"
          exit 1
        fi

        echo "✅ Found DVC tracking:"
        [ "$DVC_FILE_COUNT" -gt 0 ] && echo "   - ${DVC_FILE_COUNT} .dvc file(s) in data/${DATASET}/"
        if [ "$LOCK_FILE_COUNT" -gt 0 ]; then
          echo "   - ${LOCK_FILE_COUNT} dvc.lock file(s) in pipelines/"
          echo "$LOCK_FILES" | while read -r lock; do
            [ -n "$lock" ] && echo "     - ${lock}"
          done
        fi

        # Save temp dir path for next step
        echo "temp-dir=${TEMP_DIR}" >> $GITHUB_OUTPUT
        echo "dvc-file-count=${DVC_FILE_COUNT}" >> $GITHUB_OUTPUT
        echo "lock-file-count=${LOCK_FILE_COUNT}" >> $GITHUB_OUTPUT

    # =========================================================================
    # Step 3: Verify data exists in remote storage (optional)
    # =========================================================================
    - name: 🔍 Verify remote storage
      id: verify-remote
      if: inputs.verify-remote == 'true'
      shell: bash
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.aws-access-key-id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-secret-access-key }}
        AWS_ENDPOINT_URL: ${{ inputs.aws-endpoint-url }}
      run: |
        DATASET="${{ inputs.dataset }}"
        TEMP_DIR="${{ steps.check-tracking.outputs.temp-dir }}"

        echo "🔍 Verifying data exists in remote storage..."

        # Validate credentials
        if [ -z "${AWS_ACCESS_KEY_ID}" ] || [ -z "${AWS_SECRET_ACCESS_KEY}" ]; then
          echo "❌ AWS credentials required for remote verification"
          exit 1
        fi

        # Install AWS CLI if needed
        if ! command -v aws &> /dev/null; then
          echo "📦 Installing AWS CLI..."
          curl -sL "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "/tmp/awscliv2.zip"
          unzip -q /tmp/awscliv2.zip -d /tmp
          /tmp/aws/install -i ~/.local/aws-cli -b ~/.local/bin --update
          rm -rf /tmp/awscliv2.zip /tmp/aws
          echo "✅ AWS CLI installed"
        fi

        # Ensure aws is in PATH
        export PATH="$HOME/.local/bin:$PATH"

        if ! command -v aws &> /dev/null; then
          echo "❌ AWS CLI not found in PATH"
          echo "   PATH: $PATH"
          exit 1
        fi

        # Build S3 options
        S3_OPTS="--no-verify-ssl"
        [ -n "${AWS_ENDPOINT_URL}" ] && S3_OPTS="${S3_OPTS} --endpoint-url ${AWS_ENDPOINT_URL}"

        # Debug: verify credentials are set
        echo ""
        echo "DEBUG:"
        echo "   Endpoint: ${AWS_ENDPOINT_URL}"
        echo "   Access Key length: ${#AWS_ACCESS_KEY_ID}"
        echo "   Access Key prefix: ${AWS_ACCESS_KEY_ID:0:4}****"
        echo "   Secret Key length: ${#AWS_SECRET_ACCESS_KEY}"
        echo "   S3 Options: ${S3_OPTS}"
        echo ""

        # Test with a direct command first
        echo "   Testing direct S3 command..."
        aws --version
        echo ""
        aws s3 ls s3://dvcstore/ ${S3_OPTS} --max-items 1 2>&1 || true
        echo ""

        cd "${TEMP_DIR}"

        MISSING_COUNT=0
        CHECKED_COUNT=0

        # Check .dvc files
        for dvc_file in $(find "data/${DATASET}" -name "*.dvc" 2>/dev/null); do
          MD5=$(grep -E "^md5:" "$dvc_file" 2>/dev/null | awk '{print $2}' | head -1)
          if [ -n "$MD5" ] && [ "$MD5" != "null" ]; then
            OBJECT_PATH="files/md5/${MD5:0:2}/${MD5:2}"
            if ! aws s3api head-object ${S3_OPTS} --bucket dvcstore --key "${OBJECT_PATH}" >/dev/null 2>&1; then
              echo "   ⚠️  Missing: ${MD5:0:2}/${MD5:2} (from ${dvc_file})"
              MISSING_COUNT=$((MISSING_COUNT + 1))
            fi
            CHECKED_COUNT=$((CHECKED_COUNT + 1))
          fi
        done

        # Check dvc.lock files
        for lock_file in $(find "pipelines" -path "*${DATASET}*" -name "dvc.lock" 2>/dev/null); do
          for md5 in $(grep -E "^\s+md5:" "$lock_file" 2>/dev/null | awk '{print $2}'); do
            if [ -n "$md5" ] && [ "$md5" != "null" ]; then
              OBJECT_PATH="files/md5/${md5:0:2}/${md5:2}"
              if ! aws s3api head-object ${S3_OPTS} --bucket dvcstore --key "${OBJECT_PATH}" >/dev/null 2>&1; then
                echo "   ⚠️  Missing: ${md5:0:2}/${md5:2} (from ${lock_file})"
                MISSING_COUNT=$((MISSING_COUNT + 1))
              fi
              CHECKED_COUNT=$((CHECKED_COUNT + 1))
            fi
          done
        done

        # Report results
        if [ ${MISSING_COUNT} -gt 0 ]; then
          echo ""
          echo "❌ ${MISSING_COUNT}/${CHECKED_COUNT} data objects missing from remote storage"
          echo "   Run 'dvc push' in the data-registry repo to fix this."
          exit 1
        fi

        if [ ${CHECKED_COUNT} -eq 0 ]; then
          echo "⚠️  No MD5 hashes found to verify"
        else
          echo "✅ All ${CHECKED_COUNT} data objects verified in remote storage"
        fi

    # =========================================================================
    # Step 4: Cleanup and summary
    # =========================================================================
    - name: 🧹 Cleanup
      if: always()
      shell: bash
      run: |
        TEMP_DIR="${{ steps.check-tracking.outputs.temp-dir }}"
        [ -n "${TEMP_DIR}" ] && [ -d "${TEMP_DIR}" ] && rm -rf "${TEMP_DIR}"

        echo ""
        echo "✅ Resolved: ${{ inputs.dataset }} @ ${{ steps.resolve-tag.outputs.resolved-version }}"
        echo "   Full tag: ${{ steps.resolve-tag.outputs.full-tag }}"
