# .github/actions/setup-argo/action.yaml
name: 'Setup Argo Workflows CLI'
description: 'Install Argo CLI and verify connectivity (requires kubectl to be configured first)'

inputs:
  version:
    description: 'Argo CLI version (e.g., v3.5.8). Leave empty for latest.'
    required: false
    default: ''
  verify:
    description: 'Verify Argo connectivity'
    required: false
    default: 'true'
  namespace:
    description: 'Namespace to verify connectivity against'
    required: false
    default: 'mlops'

outputs:
  argo-path:
    description: 'Path to argo binary'
    value: ${{ steps.install.outputs.argo-path }}
  argo-version:
    description: 'Installed argo version'
    value: ${{ steps.install.outputs.argo-version }}

runs:
  using: 'composite'
  steps:
    - name: 🔧 Install Argo CLI
      id: install
      shell: bash
      run: |
        if command -v argo &> /dev/null; then
          INSTALLED_VERSION=$(argo version --short 2>/dev/null | head -1 || echo "unknown")
          echo "✅ argo already installed: $(which argo) (${INSTALLED_VERSION})"
          echo "argo-path=$(which argo)" >> $GITHUB_OUTPUT
          echo "argo-version=${INSTALLED_VERSION}" >> $GITHUB_OUTPUT
        else
          echo "📦 Installing Argo CLI..."

          # Determine version
          if [ -n "${{ inputs.version }}" ]; then
            VERSION="${{ inputs.version }}"
          else
            VERSION=$(curl -sL https://api.github.com/repos/argoproj/argo-workflows/releases/latest | jq -r '.tag_name')
          fi

          echo "📦 Installing version: ${VERSION}"

          # Download and install
          curl -sLO "https://github.com/argoproj/argo-workflows/releases/download/${VERSION}/argo-linux-amd64.gz"
          gunzip argo-linux-amd64.gz
          chmod +x argo-linux-amd64
          mkdir -p ~/.local/bin
          mv argo-linux-amd64 ~/.local/bin/argo
          echo "$HOME/.local/bin" >> $GITHUB_PATH

          echo "argo-path=$HOME/.local/bin/argo" >> $GITHUB_OUTPUT
          echo "argo-version=${VERSION}" >> $GITHUB_OUTPUT
          echo "✅ Argo CLI installed to ~/.local/bin/argo"
        fi

    - name: 🔍 Verify Argo connectivity
      if: inputs.verify == 'true'
      shell: bash
      run: |
        echo "🔍 Verifying Argo connectivity in namespace '${{ inputs.namespace }}'..."

        # Add to path for this step
        export PATH="$HOME/.local/bin:$PATH"

        if ! argo list -n ${{ inputs.namespace }} --limit 1 &> /dev/null; then
          echo "❌ Failed to connect to Argo Workflows in namespace '${{ inputs.namespace }}'"
          echo "   Make sure:"
          echo "   - kubectl is configured correctly"
          echo "   - Argo Workflows is installed in the cluster"
          echo "   - You have permissions to access namespace '${{ inputs.namespace }}'"
          exit 1
        fi

        echo "✅ Argo connectivity verified (namespace: ${{ inputs.namespace }})"
