name: Update Code Quality Image
on:
  push:
    paths:
      - "containers/code-quality/Dockerfile"
      - ".github/workflows/ci-update-code-quality-image.yaml"

jobs:
  build:
    uses: exploring-gh-organizations/called/.github/workflows/docker.yaml@main
    with:
      repo-name: "code-quality"
      context: "containers/code-quality"
      build-args: |
        PRECOMMIT_CONFIG_PATH=../../.pre-commit-config.yaml
    secrets:
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
